### ISSUE TITLE
Add your socials to this repository

### ISSUE THREAD

**Issue by mariahlaqua** [shesharpnl/knowledge-hub#14]
## Description

Let's add your socials to this repository to connect with other Sharpies!

---

### 📢 Only PRs from SheSharp's women and underrepresented gender members will be accepted

Please provide your Slack handle in the description when you create a pull request.

Joining [our Slack](https://www.shesharp.co/slack) is the way to join our community!

---

## How to add your socials to the repository

In the `socials.md` file, add the links to your social accounts.

**Comment by ZeeshanMukhtar1** [comment]
@mariahlaqua kindly assign me this issue under hacktoberfest label, I wanna add my social in social.MD, 
 As a "Zeeshan Mukhtar" i already joined your community on slack

**Comment by mariahlaqua** [comment]
Hey @ZeeshanMukhtar1 ! This is the one issue that doesn't require assignment :) Thanks for asking, I've added a label to make that clear for future PRs! Feel free to submit your PR whenever. 💯

**Comment by ZeeshanMukhtar1** [comment]
@mariahlaqua Hi, thanks for letting me know ..! 
@adiati98 I have made the requested changes including the removal of .gitmodule and the addition of a separate md file and pushed the code to my forked branch when I try to make a PR it says this will merge automatically.plz take a look at this and let me know if any other things i can do , 
 thanks
