### ISSUE TITLE
New Open Source page

### ISSUE THREAD

**Issue by saragerion** [shesharpnl/knowledge-hub#15]
# Suggestion/Improvement

## Description

I would like to suggest the creation of a new "Open Source" page in our knowledge hub repository. This page aims to provide valuable resources and guidance for individuals looking to get started with open source or enhance their contributions to existing projects. The content will cover various aspects, from finding your first open-source project to effectively communicating with project maintainers.

## Motivation

Open source is a crucial aspect of the tech community, fostering collaboration and skill development. By creating a dedicated "Open Source" page, we aim to centralize resources and insights to make it easier for individuals, especially those new to open source, to navigate and contribute effectively. 

The page will empower users with actionable items and guide them through the process of becoming active contributors.

Moreover, this page represents an **opportunity for our community members to showcase their expertise and insights**. We encourage community members to contribute tech content they created, such as blog posts, videos, and other valuable resources, which will be featured in the respective sections of the "Open Source" page. This not only enhances the richness of the page but also provides a platform for community members to share their experiences and knowledge with a broader audience.

## Implementation

The "Open Source" page will consist of different sections, each focusing on specific intents, goals, and actionable items for readers. In addition, each section will incorporate links to related articles, videos, and tech content created by SheSharp's community, offering a rich and diverse set of resources. 

This could be a section:

###  Find An Open-Source Project

This section can feature:
- Tips on choosing a project aligned with personal interests and skill level
- Curated list of beginner-friendly projects across different technologies
- Links to related articles and videos by SheSharp's community members sharing their tips

These are just examples to give an idea.

Feel free to provide feedback and additional suggestions for sections and content.

**Comment by CBID2** [comment]
Can I work on this @saragerion? :)

**Comment by saragerion** [comment]
@CBID2 I'd love for you to work on this one! 

How about I create a first PR with one section with a concrete example of what I have in mind (open to your feedback of course), and then you can take over and own any other section you want?

**Comment by CBID2** [comment]
Sure @saragerion. Maybe you can do one about the "Tech Career Navigator" one?

**Comment by saragerion** [comment]
@CBID2 Upon second thought, I want to give you the choice and the opportunity to work on what you prefer first. Feel free to pick and start working on what you like.

My only ask from a maintainer perspective is to create multiple small, incremental PRs rather than one big one, so that makes things easier in terms of reviewing (possibly already your plan).

**Comment by CBID2** [comment]
> @CBID2 Upon second thought, I want to give you the choice and the opportunity to work on what you prefer first. Feel free to pick and start working on what you like.
> 
> My only ask from a maintainer perspective is to create multiple small, incremental PRs rather than one big one, so that makes things easier in terms of reviewing (possibly already your plan).

Sure @saragerion!

**Comment by CBID2** [comment]
> @CBID2 Upon second thought, I want to give you the choice and the opportunity to work on what you prefer first. Feel free to pick and start working on what you like.
> 
> My only ask from a maintainer perspective is to create multiple small, incremental PRs rather than one big one, so that makes things easier in terms of reviewing (possibly already your plan).

Should I do this as a Markdown file in the `resources` folder @saragerion? I'm somewhat struggling with doing this in small PRs.

**Comment by saragerion** [comment]
> Should I do this as a Markdown file in the resources folder @saragerion? 

yes sounds good!

> I'm somewhat struggling with doing this in small PRs.

A possible approach on how to break this down into smaller, incremental PRs.

First PR's goal: create the page draft, with empty content and only the sub-titles that represent possible intents or goals.
So you create a PR where you:
- Create the `resources/open-source.md` file
- Add page sub-titles like "Find an open-source project", etc. These page sections have titles but no content yet, you can write TODO for each of them.
- Link the open-source file in the readme.

Second PR's goal: write content in the section "Find an open-source project".
- Complete one section 

Third PR's goal: write content in another section of your choice
- Complete another section

And so on :D

**Comment by CBID2** [comment]
> > Should I do this as a Markdown file in the resources folder @saragerion?
> 
> yes sounds good!
> 
> > I'm somewhat struggling with doing this in small PRs.
> 
> A possible approach on how to break this down into smaller, incremental PRs.
> 
> First PR's goal: create the page draft, with empty content and only the sub-titles that represent possible intents or goals. So you create a PR where you:
> 
> * Create the `resources/open-source.md` file
> * Add page sub-titles like "Find an open-source project", etc. These page sections have titles but no content yet, you can write TODO for each of them.
> * Link the open-source file in the readme.
> 
> Second PR's goal: write content in the section "Find an open-source project".
> 
> * Complete one section
> 
> Third PR's goal: write content in another section of your choice
> 
> * Complete another section
> 
> And so on :D

Did the first PR @saragerion! :) I'm going to the second one tomorrow.

**Comment by CBID2** [comment]
> > Should I do this as a Markdown file in the resources folder @saragerion?
> 
> yes sounds good!
> 
> > I'm somewhat struggling with doing this in small PRs.
> 
> A possible approach on how to break this down into smaller, incremental PRs.
> 
> First PR's goal: create the page draft, with empty content and only the sub-titles that represent possible intents or goals. So you create a PR where you:
> 
> * Create the `resources/open-source.md` file
> * Add page sub-titles like "Find an open-source project", etc. These page sections have titles but no content yet, you can write TODO for each of them.
> * Link the open-source file in the readme.
> 
> Second PR's goal: write content in the section "Find an open-source project".
> 
> * Complete one section
> 
> Third PR's goal: write content in another section of your choice
> 
> * Complete another section
> 
> And so on :D

I finished the second PR @saragerion! 😄 It's PR #29.

**Comment by CBID2** [comment]
Made the final PR @saragerion! :) It's #30

**Comment by CBID2** [comment]
@saragerion, since I made this contribution, I highly recommend closing this issue for organizational reasons.

**Comment by adiati98** [comment]
Closing this issue as completed with PRs #28, #29 and #30.

@saragerion feel free to reopen the issue if necessary. We are closing this for now to avoid dispute. 🙂
