### ISSUE TITLE
New "Tech Career Path Navigator" section

### ISSUE THREAD

**Issue by saragerion** [shesharpnl/knowledge-hub#16]
# Suggestion/Improvement

## Description

I would like to propose a new section "Tech Career Path Navigator"  that would list and provide information on different career paths in the tech industry. 

I personally hate the name "Tech Career Path Navigator", but I cannot think of anything better or more suggestive. Let's find a better title ;)

## Motivation

Today, there are several factors that contribute to the challenges that individuals, especially those from underrepresented groups, face when trying to determine which tech role to pursue:

- People new to the tech industry may not be aware of the existence of many different role types, inside or outside engineering. 
- The pathways to those roles are not always clear. Understanding the skills and qualifications required for different positions can be confusing for newcomers.
- Information about various roles may be scattered and not easily accessible.
- Stereotypes and biases can influence perceptions of certain roles.
- The tech industry is dynamic and constantly evolving, with new roles emerging regularly. Keeping up with these changes can be overwhelming, especially for newcomers.

And much more.

## Implementation (if applicable)

Each career path page could contain the following information (in no particular order):
- day-to-day responsibilities
- technical skills and soft skills required 
- trends, advancements, and challenges related to the role
- job market demand
- work-life balance
- salary expectations
- career progression and long-term career goals
- why not to pursue this specific path
- communities and networking opportunities
- tools and technologies
- success stories and profiles

**Comment by CBID2** [comment]
How about this as a title @saragerion:
"Pathways"

**Comment by saragerion** [comment]
This could be one source of inspiration to cover a list of jobs that are competitive in the current job market:
https://www.pluralsight.com/resources/blog/it-ops/best-paying-tech-jobs-2024
