### ISSUE TITLE
Fix the Table of Content on the README

### ISSUE THREAD

**Issue by adiati98** [shesharpnl/knowledge-hub#33]
# Suggestion/Improvement

🌟 Hi there! We're excited to hear your suggestions and ideas for making this project better. Thank you for contributing to our community!

## Description

There is a Table of Content in the README file, however, it's quite all over the place without a title.

![SheSharp TOC](https://github.com/shesharpnl/knowledge-hub/assets/45172775/a3fe549a-a2f2-4582-89ce-9896e0e4f503)

## Motivation

Having a title for the Table of Content and make it a section will make the README tidier.

## Implementation (if applicable)

- Add an `h2` with text: Table of Contents.
- Remove the first `<li>` (SheSharp Knowledge Hub) as we don't need to navigate to it from the Table of Content.

**Comment by dyaramatreya** [comment]
@adiati98 Raised the PR #35 to close this issue. Please review and approve the PR.
Thanks
