### ISSUE TITLE
Adding Twitter Accounts from Slack

### ISSUE THREAD

**Issue by TessavWalstijn** [shesharpnl/knowledge-hub#4]
In Pull Request: https://github.com/shesharpnl/knowledge-hub/pull/3  
  
[I asked about adding Twitter accounts.](https://github.com/shesharpnl/knowledge-hub/pull/3#discussion_r1009186296)
> We could add Twitter as well, a while back there was some one asking about it.  
> You are not obligated to include this in any way!
> 
> Slack: https://she-sharp.slack.com/archives/CPHESUZ5H/p1664192962620809

So I made a ticked here to be picked up by me or someone else.

**Comment by mariahlaqua** [comment]
I'm closing this. I think we should improve the documentation first. Also Twitter is no more.
