### ISSUE TITLE
Improve linked content with descriptions and optionally an image

### ISSUE THREAD

**Issue by mariahlaqua** [shesharpnl/knowledge-hub#53]
# Suggestion/Improvement

Currently, our links to external resources for learning are not very descriptive. Improve one or more links by adding a description, and optionally a screenshot or gif that provides more context for readers to the linked content.

## Description

For example, a link that says only "Codum" can be improved to provide more information in the link itself such as:

"Codum engineering accountability buddy platform"
Codum runs multiple cohorts a year. They pair individuals who form a team of two. These two define a goal for themselves and hold each other accountable for achieving that goal within the timeframe of the cohort.

## Motivation

We have great information on other pages of the knowledge-hub, we should raise the quality of our links to external content, to match other information.

## Implementation (if applicable)

Choose one or more links to improve.

**Comment by RitaDee** [comment]
I want to contribute to this.

**Comment by mariahlaqua** [comment]
> I want to contribute to this.

Thanks @RitaDee ! I've assigned you to the issue.

**Comment by mariahlaqua** [comment]
@RitaDee I pushed some changes today so you may want to update if you started on this at all. :)

**Comment by RitaDee** [comment]
> @RitaDee I pushed some changes today so you may want to update if you started on this at all. :)

Thank you for the notification. I will do a rebase.
